---
ruby_library_version:   "2.0.0"
ruby_version:           "ruby-2.0.0-p353"
ruby_checksum:          "3de4e4d9aff4682fa4f8ed2b70bd0d746fae17452fc3d3a8e8f505ead9105ad9"
ruby_download_location: "http://cache.ruby-lang.org/pub/ruby/2.0/{{ ruby_version }}.tar.bz2"

ruby_dependencies:
  - libreadline-dev
  - libssl-dev
  - libyaml-dev
  - zlib1g-dev
  - libicu-dev # for charlock_holmes gem
  # - libxslt-dev # for nokogiri gem - commented out due to this bug: https://github.com/ansible/ansible/pull/5182
  # instead of libxslt-dev, we're using libxslt1-dev libxslt1.1 which can be removed after using Ansible 1.5+
  - libxslt1-dev
  - libxslt1.1
  - libxml2-dev # for nokogiri gem

ruby_symlinks:
  - bundle
  - erb
  - gem
  - irb
  - rake
  - rdoc
  - ri
  - ruby
  - testrb

ruby_location: "/opt/{{ ruby_version }}"